name: Main Workflow

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        flake8 .

  editorconfig-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Run editorconfig-checker
      run: editorconfig-checker

  markdown-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install cli-markdown
      run: npm install -g cli-markdown

    - name: Run cli-markdown on all .md files
      run: npx cli-markdown *.md

  unittests:
    runs-on: ubuntu-latest

    needs: [linter]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          python -m unittest src/app_test.py

  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4.1.0 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
