name: Main Workflow

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        flake8 .

  editorconfig-checker:
    runs-on: ubuntu-latest

    needs: linter

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Run editorconfig-checker
      run: editorconfig-checker

  markdown-checker:
    runs-on: ubuntu-latest

    needs: linter

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install cli-markdown
      run: npm install -g cli-markdown

    - name: Run cli-markdown on all .md files
      run: npx cli-markdown *.md

  sonarqube:
    runs-on: ubuntu-latest

    needs: [linter, editorconfig-checker]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION_KEY }}

  snyk:
    runs-on: ubuntu-latest

    needs: [linter, editorconfig-checker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Snyk with npm
        run: npm install -g snyk

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run snyk
        run: npx snyk test --file="./src/requirements.txt"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  unittests:
    runs-on: ubuntu-latest

    needs: [linter, sonarqube, snyk]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          python -m unittest src/app_test.py

  gitleaks:
    runs-on: ubuntu-latest

    needs: linter

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITLEAKS_TOKEN }}

  database-migrate-check:
    if: false               # diable job: Due to Flyway problems.
    runs-on: ubuntu-latest

    needs: unittests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flyway
      run: |
        wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz
        tar -xvf flyway-commandline-11.1.0-linux-x64.tar.gz
        sudo mv flyway-11.1.0 /usr/local/flyway
        export PATH=$PATH:/usr/local/flyway

    - name: Run Flyway migration check
      run: |
        /usr/local/flyway/flyway -url=jdbc:mysql://localhost:3306/your_db -user=your_user -password=your_password -locations=filesystem:sql check
