name: Main Workflow

on: [push]

jobs:
  Linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        flake8 .

  EditorConfig-Checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Verify Node.js installation
      run: node -v

    - name: Install editorconfig-checker
      run: npm install -g editorconfig-checker

    - name: Run editorconfig-checker with verbose logging
      run: editorconfig-checker . --verbose
