name: Main Workflow

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        flake8 .

  editorconfig-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Run editorconfig-checker
      run: editorconfig-checker

  Markdown-Checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install cli-markdown
      run: npm install -g cli-markdown

    - name: Run cli-markdown on all .md files
      run: find . -name "*.md" -exec cli-markdown {} \;
